const express = require('express');
const router = express.Router();
const debugController = require('../controllers/debugController');
router.get('/send-test-email', debugController.sendTestEmail);
router.get('/verify-smtp', debugController.verifySmtp);
router.post('/populate-leaderboard', debugController.populateLeaderboard);
router.get('/leaderboard-stats', debugController.getLeaderboardStats);
router.post('/recalculate-leaderboard', debugController.recalculateLeaderboard);
router.post('/reset-monthly-leaderboard', debugController.resetMonthlyLeaderboard);
module.exports = router;
