const express = require('express');
const router = express.Router();
const monthlySavingsTierController = require('../controllers/monthlySavingsTierController');
const { protect } = require('../utils/authMiddleware');
router.use(protect);
router.get('/current', monthlySavingsTierController.getCurrentMonthTier);
router.get('/history', monthlySavingsTierController.getMonthlyTiersHistory);
router.post('/calculate', monthlySavingsTierController.calculateCurrentMonthTier);
router.get('/stats', monthlySavingsTierController.getTierStats);
module.exports = router;
