const express = require('express');
const router = express.Router();
const userController = require('../controllers/userController');
const { protect } = require('../utils/authMiddleware');
router.use(protect);
router.get('/points', userController.getUserPoints);
router.get('/points/history', userController.getPointsHistory);
router.get('/achievements', userController.getUserAchievements);
router.get('/usage-stats', userController.getUserUsageStats);
module.exports = router;
